package io.flutter.plugins;

import androidx.annotation.Keep;
import androidx.annotation.NonNull;
import io.flutter.Log;

import io.flutter.embedding.engine.FlutterEngine;

/**
 * Generated file. Do not edit.
 * This file is generated by the Flutter tool based on the
 * plugins that support the Android platform.
 */
@Keep
public final class GeneratedPluginRegistrant {
  private static final String TAG = "GeneratedPluginRegistrant";
  public static void registerWith(@NonNull FlutterEngine flutterEngine) {
    try {
      flutterEngine.getPlugins().add(new com.bbflight.background_downloader.BDPlugin());
    } catch (Exception e) {
      Log.e(TAG, "Error registering plugin background_downloader, com.bbflight.background_downloader.BDPlugin", e);
    }
    try {
      flutterEngine.getPlugins().add(new io.iden3.circom_witnesscalc.CircomWitnesscalcPlugin());
    } catch (Exception e) {
      Log.e(TAG, "Error registering plugin circom_witnesscalc, io.iden3.circom_witnesscalc.CircomWitnesscalcPlugin", e);
    }
    try {
      flutterEngine.getPlugins().add(new com.rapidsnark.flutter_rapidsnark.FlutterRapidsnarkPlugin());
    } catch (Exception e) {
      Log.e(TAG, "Error registering plugin flutter_rapidsnark, com.rapidsnark.flutter_rapidsnark.FlutterRapidsnarkPlugin", e);
    }
    try {
      flutterEngine.getPlugins().add(new com.it_nomads.fluttersecurestorage.FlutterSecureStoragePlugin());
    } catch (Exception e) {
      Log.e(TAG, "Error registering plugin flutter_secure_storage, com.it_nomads.fluttersecurestorage.FlutterSecureStoragePlugin", e);
    }
    try {
      flutterEngine.getPlugins().add(new me.albemala.md5_file_checksum.Md5FileChecksumPlugin());
    } catch (Exception e) {
      Log.e(TAG, "Error registering plugin md5_file_checksum, me.albemala.md5_file_checksum.Md5FileChecksumPlugin", e);
    }
    try {
      flutterEngine.getPlugins().add(new dev.steenbakker.mobile_scanner.MobileScannerPlugin());
    } catch (Exception e) {
      Log.e(TAG, "Error registering plugin mobile_scanner, dev.steenbakker.mobile_scanner.MobileScannerPlugin", e);
    }
    try {
      flutterEngine.getPlugins().add(new dev.fluttercommunity.plus.packageinfo.PackageInfoPlugin());
    } catch (Exception e) {
      Log.e(TAG, "Error registering plugin package_info_plus, dev.fluttercommunity.plus.packageinfo.PackageInfoPlugin", e);
    }
    try {
      flutterEngine.getPlugins().add(new io.flutter.plugins.pathprovider.PathProviderPlugin());
    } catch (Exception e) {
      Log.e(TAG, "Error registering plugin path_provider_android, io.flutter.plugins.pathprovider.PathProviderPlugin", e);
    }
    try {
      flutterEngine.getPlugins().add(new com.baseflow.permissionhandler.PermissionHandlerPlugin());
    } catch (Exception e) {
      Log.e(TAG, "Error registering plugin permission_handler_android, com.baseflow.permissionhandler.PermissionHandlerPlugin", e);
    }
    try {
      flutterEngine.getPlugins().add(new io.iden3.polygonid_flutter_sdk.PolygonIdSdkPlugin());
    } catch (Exception e) {
      Log.e(TAG, "Error registering plugin polygonid_flutter_sdk, io.iden3.polygonid_flutter_sdk.PolygonIdSdkPlugin", e);
    }
  }
}
